services:
  molt-guard:
    build: .
    container_name: molt-guard
    ports:
      - "11434:3005"
    environment:
      - OLLAMA_URL=${OLLAMA_URL}
      - VALIDATION_MODE=${VALIDATION_MODE:-Remote}
      - PROMPT_SENSITIVITY=${PROMPT_SENSITIVITY:-Medium}
      - GUARD_MODEL=${GUARD_MODEL:-granite3-guardian:latest}
    networks:
      - infrastructure
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  infrastructure:
    external: true
    name: global_infrastructure